version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    command: mysqld --init-file="/docker-entrypoint-initdb.d/dump.sql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=BD_BENERGY_P5
    ports:
      - 3306:3306
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - backend

  server:
    depends_on:
      - mysqldb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=BD_BENERGY_P5
      - DB_PORT=3306
    networks:
      - backend
      - frontend

  client:
    depends_on:
      - server
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL=
    ports:
      - 3001:3000
    networks:
      - frontend  

volumes: 
  db:

networks:
  backend:
  frontend: